
name: spring-pet-clinic

trigger:
  - main

pool: Default


parameters:
  - name: goal
    displayName: Maven Goal 
    type: string
    default: 'package'
    values:
      - 'package' 
      - clean package
      - install

steps:
  - task: Maven@4
    displayName: Maven Build
    inputs:
      mavenPOMFile: 'pom.xml'
      goals: 'package'
      testResultsFiles: '**/surefire-reports/TEST-*.xml'